shoppulse:
  target: dev
  outputs:
    dev: 
      type: postgres
      threads: 1
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      port: 5432
      user: "{{ env_var('DBT_USERNAME', 'shoppulse') }}"
      pass: "{{ env_var('DBT_PASSWORD', 'shoppulse_secret') }}"
      dbname: shoppulse
      schema: public